name = "kitty"
version = "0.47.4"
description = "Emulador de terminal rápido baseado em GPU"
source = "https://github.com/kovidgoyal/kitty/archive/refs/tags/v0.47.4.tar.gz"
dependencies = ["harfbuzz", "zlib", "libpng"]

[phases]
build = """
# 1. Abre a função 'def is_font_present' no setup.py e injeta um 'return True' logo no início dela
sed -i '/def is_font_present/a \\    return True' setup.py

# 2. Limpa o ambiente para evitar interferências antigas
unset FONTCONFIG_FILE
export KITTY_NO_FONTCONFIG_CHECK=1

# 3. Roda o build do Kitty
python3 setup.py linux-package
"""
package = """
mkdir -p $pkgdir/usr
cp -r linux-package/* $pkgdir/usr/
"""
